title: "Y-Foundry Docs"
description: Mutably Good Documentation
logo: "/assets/images/horizontal_logo_orange-white.png"

email: admin@yfoundry.io
twitter_username: YFoundryDAO
github_username: yfoundry

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: yfd
callouts_level: loud # or quiet
callouts:
  highlight: 
    title: ğŸŒˆ Highlight
    color: yellow
  important:
    title: âš¡ Important
    color: blue
  new:
    title: âœ¨ New  âœ¨
    color: pink
  note:
    title: ğŸ“ Note
    color: purple
  warning:
    title: âš ï¸ Warning
    color: red
  gov:
    title: ğŸ—³ï¸ Governance
    color: green

# Aux links for the upper right navigation
aux_links:
  "Medium":
    - "//blog.yfoundry.io/"
  "Discord":
    - "//discord.yfoundry.io"
  "Twitter": 
    - "//twitter.yfoundry.io"
  "Telegram":
    - "//telegram.yfoundry.io"
  "Github":
    - "//source.yfoundry.io"
  "Website":
    - "//yfoundry.io/"

aux_links_new_tab: true



# Footer content
# appears at the bottom of every page's main content

# Back to top link
#back_to_top: true
#back_to_top_text: "Back to top"

footer_content: ""

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit in Github"
gh_edit_repository: "https://github.com/Y-Foundry-DAO/yfd-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Define Jekyll collections
collections_dir: docs
collections:
  guides:
    permalink: "/:collection/:path/"
    output: true
  yfoundry:
    permalink: "/:collection/:path/"
    output: true
  govern:
    permalink: "/:collection/:path/"
    output: true
  develop:
    permalink: "/:collection/:path/"
    output: true
  test:
    permalink: "/:collection/:path/"
    output: true
  essentials:
    permalink: "/:collection/:path/"
    output: true
  tokenomics:
    permalink: "/:collection/:path/"
    output: true
  community:
    permalink: "/:collection/:path/"
    output: true
  info:
    permalink: "/:collection/:path/"
    output: true
  clean:
    permalink: "/:collection/:path/"
    output: true
  
just_the_docs:
  collections:
    yfoundry:
      name: Y-Foundry DAO
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    guides:
      name: Guides
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    essentials:
      name: ğŸ““ Essentials
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    govern:
      name: ğŸ›ï¸ Governance
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    tokenomics:
      name: Tokenomics
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    develop:
      name: ğŸ’» Develop
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    test:
      name: ğŸ§ª Test
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    info:
      name: ğŸ›ï¸ Info
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    clean:
      name: Clean
      nav_exclude: true
      nav_fold: false
      search_exclude: false

plugins:
  - jekyll-default-layout
  - jekyll-feed
